Controllers/PetController.cs
using Microsoft.AspNetCore.Mvc;
using PetTracking.Models;
using StackExchange.Redis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using System.Reflection.Metadata;
using Microsoft.AspNetCore.Http;
using Microsoft.Web.Helpers;

namespace PetTracking.Controllers
{
    public class PetController : Controller
    {

        private readonly IPetRepository petRepository;
        private readonly IPetOwnerRepository petOwnerRepository;

        public PetController(IPetRepository pr, IPetOwnerRepository or)
        {
            petRepository = pr;

            petOwnerRepository = or;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult PetList()
        {
            return View(petRepository.AllPets);
        }


        [HttpPost]
        public IActionResult PetList(string search)
        {
            if (!string.IsNullOrEmpty(search))
                return View(petRepository.AllPets.Where(p => (p.PetName.ToLower() + " " + p.PetName.ToLower()).Contains(search.ToLower())));

            return View(petRepository.AllPets);
        }

        public IActionResult AddPet()
        {
            return View(petOwnerRepository.AllPetOwners);
        }


        [HttpPost]
        public IActionResult AddPet(Pet pet)
        {
            petRepository.CreatePet(pet);

            return RedirectToAction("PetList");
        }


        public IActionResult PetDetails(int id)
        {
            return View(petRepository.GetByPetId(id));
        }

        public IActionResult EditPet(int id)
        {
            return View(petRepository.GetByPetId(id));
        }

        [HttpPost]
        public IActionResult EditPet(Pet pet)
        {
            petRepository.EditPet(pet);

            return RedirectToAction("PetDetails", pet);
        }

        public IActionResult DeletePet(int id)
        {
            return View(petRepository.GetByPetId(id));
        }

        [HttpPost]
        public IActionResult DeletePet(Pet pet)
        {
            petRepository.DeletePet(pet);

            return RedirectToAction("PetList");
        }


        public IActionResult AddPhoto(int id)
        {
            return View(petRepository.GetByPetId(id));
        }

        [HttpPost]
        public IActionResult AddPhoto(IFormFile photo, int petId)
        {
            petRepository.AddPhoto(photo, petId);

            return RedirectToAction("PetList");
        }




        //[HttpPost]
        //public async Task<ActionResult> Register(Pet model)
        //{

        //}

    }
}

Controllers/PetOwnerController.cs
using Microsoft.AspNetCore.Mvc;
using PetTracking.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PetTracking.Controllers
{
    public class PetOwnerController : Controller
    {

        private readonly IPetOwnerRepository petOwnerRepository;

        public PetOwnerController(IPetOwnerRepository r)
        {
            petOwnerRepository = r;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult OwnerList()
        {
            return View(petOwnerRepository.AllPetOwners);
        }

        [HttpPost]
        public IActionResult OwnerList(int order, int first, int last, string search)
        {
            
            //if (order == 1)
            //{
            //    if (first > last)
            //        return View(petOwnerRepository.AllPetOwners.OrderBy(p => p.Id));

            //    else
            //        return View(petOwnerRepository.AllPetOwners.OrderByDescending(p => p.Id));
            //}
            //else if (order == 2)
            //{


            //    if (first < last)
            //        return View(petOwnerRepository.AllPetOwners.OrderByDescending(p => p.Pets.Count));

            //    else
            //        return View(petOwnerRepository.AllPetOwners.OrderBy(p => p.Pets.Count));


            //}

            if(!string.IsNullOrEmpty(search))
                return View(petOwnerRepository.AllPetOwners.Where(p => (p.FirstName.ToLower() + " " + p.LastName.ToLower()).Contains(search.ToLower())));

            return View(petOwnerRepository.AllPetOwners);
        }



        public IActionResult OwnerDetails(int id)
        {
            return View(petOwnerRepository.GetByPetOwnerId(id));
        }

        public IActionResult AddPetOwner()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddPetOwner(PetOwner owner)
        {
            petOwnerRepository.CreatePetOwner(owner);

            return RedirectToAction("OwnerList");
        }

        public IActionResult EditOwner(int id)
        {
            return View(petOwnerRepository.GetByPetOwnerId(id));
        }

        [HttpPost]
        public IActionResult EditOwner(PetOwner owner)
        {
            petOwnerRepository.EditPetOwner(owner);

            return RedirectToAction("OwnerDetails", owner);
        }

        public IActionResult DeleteOwner(int id)
        {
            return View(petOwnerRepository.GetByPetOwnerId(id));
        }


        [HttpPost]
        public IActionResult DeleteOwner(PetOwner owner)
        {
            petOwnerRepository.DeletePetOwner(owner);

            return RedirectToAction("OwnerList");
        }

    }
}

Views/Shared/_Header.cshtml
<div class="text-center">
    <h1 class="display-4">eBlu Pet Tracking</h1>

    <hr />
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]eBlu Pet Tracking</title>
    

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">eBlu Pet Tracking</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pet" asp-action="PetList">Pet List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PetOwner" asp-action="OwnerList">Owner List</a>
                        </li>
                        @*<li class="nav-item" style="text-align:right">
                            <partial name="_LoginPartial" style="text-align:right"/>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - eBluPetTracking - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>